# Generated by Django 4.1.7 on 2023-02-27 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 18, 20, 30, 883809, tzinfo=datetime.timezone.utc)),
        ),
    ]
